## List
Built-in constructor for creating lists, a versatile data structure. It can convert iterable objects into lists, make shallow copies of existing lists, and create nested lists. Lists are mutable and support common list operations, including indexing and various list methods.

- `append()` | Add an element to the end of the list.
- `pop()` | Remove and return the last element of the list.
- `insert()` | Insert an element at a specified position.
- `index()` | Find the index of a specifc value in teh list.
- `remove()` | Remove the first occurence of a specified value.
- `len()` | Get the length of the list

In [1144]:
LIST = [1, 2, 3, 5, 6]

In [1145]:
LIST.append(2)
LIST

[1, 2, 3, 5, 6, 2]

In [1146]:
LIST.pop()
LIST.pop()
LIST

[1, 2, 3, 5]

In [1147]:
LIST.insert(1, 'hi') #(index, value)
LIST

[1, 'hi', 2, 3, 5]

In [1148]:
LIST.remove('hi') #remove 'hi' from list
LIST

[1, 2, 3, 5]

In [1149]:
n = len(LIST)
n

4

## Sets
set() is a built-in constructor in Python for creating sets, an unordered collection of unique elements. It can convert iterable objects into sets and remove duplicates. Sets are mutable, support common set operations like union and intersection, and can be used for membership testing and eliminating duplicates.

- `add()`: Add an element to the set.
- `remove()`: Remove an element from the set.
- `union()`: Perform the union of two sets.
- `intersection()`: Perform the intersection of two sets.
- `difference()`: Find the difference between two sets.

In [1150]:
SET = set((1, 1, 3, 4))
SET #only unique elements are stores, duplicates are removed

{1, 3, 4}

In [1151]:
SET.add('HI')
SET

{1, 3, 4, 'HI'}

In [1152]:
SET.remove(4)
SET

{1, 3, 'HI'}

In [1153]:
SET1 = {'HI', 5, 928}
NEW_SET = SET.union(SET1)
NEW_SET

{1, 3, 5, 928, 'HI'}

In [1154]:
NEW_SET_INT = NEW_SET.intersection(SET) # {1, 3, 5, 928, 'hi'} AND {1, 3, 'hi'} -> {1, 3, 'hi'}
NEW_SET_INT

{1, 3, 'HI'}

In [1155]:
NEW_SET_DIFF = NEW_SET.difference(SET) # {1, 3, 5, 928, 'hi'} DIFF {1, 3, 'hi'} -> {5, 928}
NEW_SET_DIFF

{5, 928}

## Dictionaries
dict() is a Python built-in constructor for creating dictionaries, a collection of key-value pairs. It can convert iterable objects or provide key-value pairs for dictionary creation. Dictionaries are mutable, unordered, and support common dictionary operations, including key access, insertion, and deletion, making them useful for data mapping.
- `get()`: Retrieve the value associated with a key.
- `keys()`: Get a list of keys in the dictionary.
- `values()`: Get a list of values in the dictionary.
- `items()`: Get a list of key-value pairs in the dictionary.
- `len()`: Get the number of key-value pairs in the dictionary.

In [1156]:
DICT = {"1" : 1, "2" : 3, "hello" : "there", 1 :  2}
DICT

{'1': 1, '2': 3, 'hello': 'there', 1: 2}

In [1157]:
s = DICT.get('hello')
print(s)
S = DICT.get('nothing here') # Should return None (defualt case of .get())
print(S)

there
None


In [1158]:
keys = DICT.keys()
keys

dict_keys(['1', '2', 'hello', 1])

In [1159]:
values = DICT.values()
values

dict_values([1, 3, 'there', 2])

In [1160]:
items = DICT.items()
items

dict_items([('1', 1), ('2', 3), ('hello', 'there'), (1, 2)])

In [1161]:
number_of_key_values = len(DICT)
number_of_key_values

4

Strings

- String manipulation: Slicing, concatenation, and searching.
- `str.split()`: Split a string into a list of substrings.
- `str.join()`: Join a list of strings into one string.
- `str.strip()`: Remove leading and trailing whitespace.
- `str.replace()`: Replace occurrences of a substring with another string.

In [1162]:
STRING = "HELLO THERE MATE!"
STRING2 = "Yes, hello there"

In [1163]:
split_str = STRING.split('T')
split_str

['HELLO ', 'HERE MA', 'E!']

In [1164]:
words = ["Hello", "world", "Python", "rocks", str(1)]
joined_string = " - ".join(words) #places ' - ' between every list element
joined_string

'Hello - world - Python - rocks - 1'

In [1165]:
joined_string += '                           '
joined_string

/Users/alexy/Library/Python/3.11/lib/python/site-packages/IPython/core/displayhook.py:275: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'


'Hello - world - Python - rocks - 1                           '

In [1166]:
joined_string.strip()

'Hello - world - Python - rocks - 1'

In [1167]:
joined_string.replace(str(1), 'forever') #(value to find, replacing value)

'Hello - world - Python - rocks - forever                           '

In [1168]:
num = str(1)
alphabet = 'a'
unicode_a = 97
print(f"1 is numeric -> {num.isalpha()}")
print(f"1 is numeric -> {num.isnumeric()}")
print(f"1 is either numeric or alphabet -> {num.isalnum()}")
print(f'1 unicode -> {ord(num)}')
print(f'a unicode conversion -> {chr(unicode_a)}')


1 is numeric -> False
1 is numeric -> True
1 is either numeric or alphabet -> True
1 unicode -> 49
a unicode conversion -> a


# NumPy Array Operations

NumPy is a powerful library for numerical operations in Python, and understanding its key methods and functions is crucial for efficient data manipulation and scientific computing. Here are some of the essential methods and functions when working with NumPy arrays:

## Array Creation

- `np.array()`: Create an array from an iterable.
- `np.zeros()`: Generate an array of zeros.
- `np.ones()`: Create an array of ones.
- `np.empty()`: Generate an uninitialized array.
- `np.arange()`: Generate an array with regularly spaced values.
- `np.linspace()`: Create an array with evenly spaced values.

## Array Shape and Dimensions

- `array.shape`: Get the shape of the array.
- `array.ndim`: Get the number of dimensions.
- `array.size`: Get the number of elements.
- `array.reshape()`: Reshape the array.

## Array Indexing and Slicing

- `array[index]`: Access elements at a specific index.
- `array[start:stop]`: Slice the array.
- `array[start:stop:step]`: Slice with a step.
- `array[condition]`: Use Boolean conditions for filtering.

## Mathematical Operations

- `np.add()`: Element-wise addition.
- `np.subtract()`: Element-wise subtraction.
- `np.multiply()`: Element-wise multiplication.
- `np.divide()`: Element-wise division.
- `np.dot()`: Compute the dot product.
- `np.sum()`, `np.mean()`, `np.max()`, `np.min()`: Basic statistics.

## Array Manipulation

- `np.append()`: Append values to an array.
- `np.concatenate()`: Concatenate arrays along an axis.
- `np.vstack()`: Vertically stack arrays.
- `np.hstack()`: Horizontally stack arrays.
- `np.split()`: Split an array into sub-arrays.
- `np.transpose()`: Transpose the array.

## Random Number Generation

- `np.random.rand()`: Generate random numbers from a uniform distribution.
- `np.random.randn()`: Generate random numbers from a standard normal distribution.
- `np.random.randint()`: Generate random integers.

## Statistics and Linear Algebra

- `np.mean()`, `np.std()`, `np.var()`: Calculate statistics.
- `np.linalg.inv()`: Compute the inverse of a matrix.
- `np.linalg.det()`: Calculate the determinant.
- `np.linalg.eig()`: Compute eigenvalues and eigenvectors.

## Array Comparison and Logical Operations

- `np.equal()`, `np.not_equal()`: Element-wise array comparison.
- `np.logical_and()`, `np.logical_or()`: Element-wise logical operations.

## Advanced Features

- Broadcasting: Understand array broadcasting for different shapes.
- Universal Functions (ufuncs): Utilize universal functions for element-wise operations.
- Masked Arrays: Handle missing or invalid data with masked arrays.

In [1169]:
import numpy as np
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [1170]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [1171]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [1172]:
empty = np.empty(5)
empty

array([1., 1., 1., 1., 1.])

In [1173]:
spaced_values = np.arange(1, 10, 2) #start idx, end idx, step size
spaced_values

array([1, 3, 5, 7, 9])

In [1174]:
linear_nums = np.linspace(1, 1000)
linear_nums

array([   1.        ,   21.3877551 ,   41.7755102 ,   62.16326531,
         82.55102041,  102.93877551,  123.32653061,  143.71428571,
        164.10204082,  184.48979592,  204.87755102,  225.26530612,
        245.65306122,  266.04081633,  286.42857143,  306.81632653,
        327.20408163,  347.59183673,  367.97959184,  388.36734694,
        408.75510204,  429.14285714,  449.53061224,  469.91836735,
        490.30612245,  510.69387755,  531.08163265,  551.46938776,
        571.85714286,  592.24489796,  612.63265306,  633.02040816,
        653.40816327,  673.79591837,  694.18367347,  714.57142857,
        734.95918367,  755.34693878,  775.73469388,  796.12244898,
        816.51020408,  836.89795918,  857.28571429,  877.67346939,
        898.06122449,  918.44897959,  938.83673469,  959.2244898 ,
        979.6122449 , 1000.        ])

In [1175]:
ARR = np.array([[1, 2], [5, 2], [44, 2], [1, 1]])
ARR.shape

(4, 2)

In [1176]:
ARR.ndim

2

In [1177]:
ARR.size

8

In [1178]:
ARR.reshape((1, 8))

array([[ 1,  2,  5,  2, 44,  2,  1,  1]])

In [1179]:
first = ARR[0]
first

array([1, 2])

In [1180]:
subset = ARR[0:3]
subset

array([[ 1,  2],
       [ 5,  2],
       [44,  2]])

In [1181]:
subset_step = ARR[0:4:2]
subset_step

array([[ 1,  2],
       [44,  2]])

In [1182]:
condition = ARR > 1
print(condition)
subset_filter = ARR[condition]
subset_filter

[[False  True]
 [ True  True]
 [ True  True]
 [False False]]


array([ 2,  5,  2, 44,  2])

In [1183]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-1, 4, -3])
np.add(arr1, arr2)

array([0, 6, 0])

In [1184]:
np.subtract(arr1, arr2)

array([ 2, -2,  6])

In [1185]:
np.multiply(arr1, arr2)

array([-1,  8, -9])

In [1186]:
np.divide(arr1, arr2)

array([-1. ,  0.5, -1. ])

In [1187]:
np.dot(arr1, arr2)

-2

In [1188]:
np.sum(arr1)

6

In [1189]:
np.mean(arr1)

2.0

In [1190]:
np.max(arr1)

3

In [1191]:
np.min(arr1)

1

In [1192]:
np.append(arr1, np.array([1]))

array([1, 2, 3, 1])

In [1193]:
new_arr = np.concatenate((arr1, arr2))
new_arr

array([ 1,  2,  3, -1,  4, -3])

In [1194]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [-1,  4, -3]])

In [1195]:
np.hstack((arr1, arr2))

array([ 1,  2,  3, -1,  4, -3])

In [1196]:
np.split(np.hstack((arr1, arr2)), 3)

[array([1, 2]), array([ 3, -1]), array([ 4, -3])]

In [1197]:
new = np.transpose(arr1)
new

array([1, 2, 3])

In [1198]:
stat_arr = np.array([1, 2, 3, 33, 3, 2])
np.mean(stat_arr)

7.333333333333333

In [1199]:
np.std(stat_arr)

11.498792207106893

In [1200]:
np.var(stat_arr)

132.22222222222223

In [1201]:
mtx = np.array([[3, 2, 1], [1, 2, 3], [3, 3, 5]])
mtx

array([[3, 2, 1],
       [1, 2, 3],
       [3, 3, 5]])

In [1202]:
inv_mtx = np.linalg.inv(mtx)
inv_mtx

array([[ 0.125, -0.875,  0.5  ],
       [ 0.5  ,  1.5  , -1.   ],
       [-0.375, -0.375,  0.5  ]])

In [1203]:
det = np.linalg.det(mtx)
det

8.000000000000002

In [1204]:
eigenvalue, eigenvector = np.linalg.eig(mtx)
print(f"Eigenvalues -> {eigenvalue}")
print(f"Eigenvector -> {eigenvector}")

Eigenvalues -> [8.         0.99999998 1.00000002]
Eigenvector -> [[ 3.48742916e-01  7.07106775e-01 -7.07106787e-01]
 [ 4.64990555e-01 -7.07106787e-01  7.07106775e-01]
 [ 8.13733471e-01  9.31563337e-09  9.31563351e-09]]


## Sorting and Searching

- Sorting: `sorted()`, `list.sort()`, `sorted(iterable, key=lambda x: ...)`.
- Binary search: `bisect.bisect()`, `bisect.bisect_left()`, `bisect.bisect_right()`.

In [1205]:
s = [(1, 'Hello'), (2, 'There'), (10, 'Big Number')]
values = [-2, 1, 2, 313, 12, -2222]
new_values = sorted(values)
new_values #Ascending order (default case)

[-2222, -2, 1, 2, 12, 313]

In [1206]:
new_values.sort(reverse=True) #Descending order
new_values

[313, 12, 2, 1, -2, -2222]

In [1207]:
#Sorting based on a key
s.sort(key=lambda x : x[0], reverse=True) #Sort based on the first index value of elements in list + reverse the order 
s

[(10, 'Big Number'), (2, 'There'), (1, 'Hello')]

In [1208]:
import bisect
value = 7 # value to place in list
sort_arr = [1,2,10, 20, 100]
insertion_point = bisect.bisect(sort_arr, value)
print(sort_arr)
print(f"Insert {value} at index {insertion_point}")

[1, 2, 10, 20, 100]
Insert 7 at index 2


In [1209]:
# Using bisect.bisect_left() to find the leftmost insertion point for a value
value = 8
leftmost_insertion_point = bisect.bisect_left(sort_arr, value)
print(f"Insert {value} at index {leftmost_insertion_point}")

Insert 8 at index 2


In [1210]:
# Using bisect.bisect_right() to find the rightmost insertion point for a value
value = 8
rightmost_insertion_point = bisect.bisect_right(sort_arr, value)
print(f"Insert {value} at index {rightmost_insertion_point}")

Insert 8 at index 2


## Recursion

- Understand recursion and implement recursive functions.

In [1211]:
def factorial(n):
    if n == 0: #base case (most recursion problem will have this)
        return 1
    else:
        return n * factorial(n - 1)

In [1212]:
result = factorial(10)
result

3628800

## Dynamic Programming

- Apply techniques like memoization (caching) to optimize recursive algorithms.

In [1213]:
fib_cache = {}

def fibonacci(n, cache):
    if n in cache:
        return cache[n]
    if n <= 1:
        result = n
    else: 
        result = fibonacci(n - 1, cache) + fibonacci(n - 2, cache)
    cache[n] = result
    return result
fib_sequence = [fibonacci(i, fib_cache) for i in range(20)]
print(fib_cache)
print(fib_sequence)


{0: 0, 1: 1, 2: 1, 3: 2, 4: 3, 5: 5, 6: 8, 7: 13, 8: 21, 9: 34, 10: 55, 11: 89, 12: 144, 13: 233, 14: 377, 15: 610, 16: 987, 17: 1597, 18: 2584, 19: 4181}
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]
